# Generated by Django 5.2.8 on 2025-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('origin_airport', models.CharField(max_length=10)),
                ('destination_airport', models.CharField(max_length=10)),
                ('scheduled_departure', models.DateTimeField()),
                ('aircraft_tail_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_base_prediction', models.FloatField(blank=True, null=True)),
                ('last_final_prediction', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
